name: secure_screen_plugin
description: A Flutter plugin that provides secure screen functionality to prevent screenshots and screen recording on Android and iOS platforms.
version: 0.1.0+1
homepage: https://github.com/YangLi-dev/secure_screen_plugin
repository: https://github.com/YangLi-dev/secure_screen_plugin
issue_tracker: https://github.com/YangLi-dev/secure_screen_plugin/issues

environment:
  sdk: ^3.9.0
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: secure_screen_plugin_android
      ios:
        default_package: secure_screen_plugin_ios

dependencies:
  flutter:
    sdk: flutter
  secure_screen_plugin_android: ^0.1.0 # 改为版本依赖
  secure_screen_plugin_ios: ^0.1.0 # 改为版本依赖
  secure_screen_plugin_platform_interface: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.0.0
